#ifndef header_h
#define header_h

String file1=
"HTTP/1.1 200 OK\r\n"
"Content-Type: text/html\r\n\r\n"
"<!DOCTYPE>\r\n"
"<html>\r\n"
"	<head><title>ISTD Workshop</title></head>\r\n"
"	<style>\r\n"
"		@import url('https://fonts.googleapis.com/css?family=Open+Sans');\r\n"
"		body{\r\n"
"			background-color : #EF5350;\r\n"
"\r\n"
"		}\r\n"
"		.title{\r\n"
"			font-size : 30px;\r\n"
"			font-family : 'Open Sans';\r\n"
"			color : white;\r\n"
"			text-align : center;\r\n"
"			margin-left: auto;\r\n"
"			margin-right : auto;\r\n"
"		}\r\n"
"		#lower{\r\n"
"			font-size: 25px;\r\n"
"		}\r\n"
"		.buttons{\r\n"
"			font-size: 15px;\r\n"
"			color : white;\r\n"
"			font-family : 'Open Sans';\r\n"
"			text-align : center;\r\n"
"			margin-top : 10px;\r\n"
"			\r\n"
"		}\r\n"
"		.left-buttons{\r\n"
"			display : flex;\r\n"
"			flex-direction : column;\r\n"
"			align-items : center;\r\n"
"		}\r\n"
"		.right-buttons{\r\n"
"			display : flex;\r\n"
"			flex-direction: column;\r\n"
"			align-items : center;\r\n"
"		}\r\n"
"		#border{\r\n"
"			border : 1px solid #fff;\r\n"
"			text-align : center;\r\n"
"			padding : 8px;\r\n"
"			border-radius : 10px;\r\n"
"			width : 150px;\r\n"
"\r\n"
"		}\r\n"
"		#border:hover, #border:active{\r\n"
"			background-color : white;\r\n"
"			color : #EF5350;\r\n"
"		}\r\n"
"		a {\r\n"
"			color: inherit;\r\n"
"			text-decoration: none;\r\n"
"		}\r\n"
"\r\n"
"	</style>\r\n"
"	<body>\r\n"
"		<div class = \"logo\">\r\n"
"		<div class = \"title\"><p>Open House 2017</p><p id = \"lower\">ISTD Workshop</p></div>\r\n"
"		<div class = \"center\">\r\n"
"			<div class = \"buttons\">\r\n"
"				<div class = \"left-buttons\">\r\n"
"					<p id = \"border\"><a href=\"red\">Red</a></p>\r\n"
"					<p id = \"border\"><a href=\"green\">Green</a></p>\r\n"
"					<p id = \"border\"><a href=\"blue\">Blue</a></p>\r\n"
"					<p id = \"border\"><a href=\"rainbow\">Rainbow</a></p>\r\n"
"				</div>\r\n"
"				<div class = \"right-buttons\">\r\n"
"					<p id = \"border\"><a href=\"custom1\">Custom 1</a></p>\r\n"
"					<p id=\"border\"><a href=\"off\">Off</a></p>\r\n"
"				</div>\r\n"
"			</div>\r\n"
"		</div>\r\n"
"	</body>\r\n"
"</html>\r\n";

#endif
