#ifndef header_h
#define header_h

String file1=
"<html>\r\n"
"<style>\r\n"
"button {\r\n"
"	font-size: 16px;\r\n"
"\r\n"
"	width: 100px;\r\n"
"	height: 50px;\r\n"
"\r\n"
"	margin: 10px;\r\n"
"	border: none;\r\n"
"	border-radius: 3px;\r\n"
"	cursor: pointer;\r\n"
"\r\n"
"	color: white;\r\n"
"	background-color: #424242;\r\n"
"}\r\n"
"\r\n"
"button:hover {\r\n"
"	box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);\r\n"
"}\r\n"
"\r\n"
"button:active {\r\n"
"	color: #808080;\r\n"
"}\r\n"
"\r\n"
"button#red {\r\n"
"	background-color: red;\r\n"
"}\r\n"
"\r\n"
"button#green {\r\n"
"	background-color: green;\r\n"
"}\r\n"
"\r\n"
"button#blue {\r\n"
"	background-color: blue;\r\n"
"}\r\n"
"</style>\r\n"
"<head>\r\n"
"	<title>NeoPixel Demo</title>\r\n"
"</head>\r\n"
"<body>\r\n"
"	<div>\r\n"
"		<a href='red'><button id='red'>RED</button></a>\r\n"
"		<a href='green'><button id='green'>GREEN</button></a>\r\n"
"		<a href='blue'><button id='blue'>BLUE</button></a>\r\n"
"		<a href='off'><button id='off'>OFF</button></a>\r\n"
"	</div>\r\n"
"	<div>\r\n"
"		<a href='custom1'><button id='custom1'>CUSTOM 1</button></a>\r\n"
"		<a href='custom2'><button id='custom2'>CUSTOM 2</button></a>\r\n"
"		<a href='custom3'><button id='custom3'>CUSTOM 3</button></a>\r\n"
"	</div>\r\n"
"</body>\r\n"
"</html>\r\n";

#endif